services:
  mysql_206:
    container_name: mysql_206
    hostname: mysql_206
    image: mysql:8
    command: 
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_206:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
